name: todo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  cloud_firestore: ^0.16.0
  cupertino_stepper: ^0.2.1
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  flutter:
    sdk: flutter
  flutter_sequence_animation: ^4.0.0
  flutter_slidable: ^3.0.0
  navbar_router: ^0.5.1
  provider: ^6.0.5
  splashscreen: ^1.2.0
# flutter_native_splash:
#   android: true
#   color: "#ffffff"
#   image: "assets/images/to-do-list-to-do.gif"
dev_dependencies:
  flutter_lints: ^2.0.0
flutter_test:
  sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
